#!/usr/bin/env node
/**
 * Build the runtime-translation dictionaries that LocaleOverlay consumes.
 *
 * Source of truth is plain JSON, so a language can be produced (and reviewed)
 * without touching TypeScript:
 *
 *   scripts/locales/en.json          the canonical English key list (an array)
 *   scripts/locales/<tag>.json       English → <tag> phrase map
 *
 * Output is one lazily-importable module per language:
 *
 *   frontend/src/lib/i18n/locales/<tag>.ts
 *
 * Usage
 *   node scripts/build-locale.mjs --all         build every language found
 *   node scripts/build-locale.mjs zh-TW ja      build the named languages
 *   node scripts/build-locale.mjs --check       report coverage/drift, write nothing
 *   node scripts/build-locale.mjs --keys        print the canonical key list stats
 *   node scripts/build-locale.mjs --split       write translation work chunks
 *
 * `--split` writes balanced chunks to `scripts/locales/parts/en-part<N>.json`
 * (+ `zh-CN-part<N>.json`, which carries the Simplified text a Traditional pass
 * starts from); that is what a translation pass reads, writing
 * `scripts/locales/out/<tag>-part<N>.json` as `{"<index>": "<translation>"}`.
 * Indexes rather than English keys mean a translation pass can never silently
 * retype a key. `scripts/merge-locale.mjs <tag>` recombines them.
 *
 * Key coverage matters: the overlay matches a whole rendered text node against a
 * key, so a language that is missing keys simply leaves those strings in
 * English. `--check` is what catches upstream copy changes drifting away from
 * the dictionaries (and what CI should run).
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DATA = join(ROOT, "scripts", "locales");
const OUT_DIR = join(ROOT, "frontend", "src", "lib", "i18n", "locales");

const readJson = (file) => JSON.parse(readFileSync(file, "utf8"));

function keys() {
  return readJson(join(DATA, "en.json"));
}

/** Languages with a source JSON present, excluding the canonical key list. */
function availableLanguages() {
  return readdirSync(DATA)
    .filter((f) => f.endsWith(".json") && f !== "en.json")
    .map((f) => f.replace(/\.json$/, ""))
    .sort();
}

function report(tag, phrases) {
  const canonical = keys();
  const known = new Set(canonical);
  const missing = canonical.filter((k) => !(k in phrases));
  const extra = Object.keys(phrases).filter((k) => !known.has(k));
  const identity = Object.entries(phrases).filter(([k, v]) => k === v).map(([k]) => k);
  const effective = Object.keys(phrases).length - identity.length;
  return {
    tag,
    total: canonical.length,
    covered: Object.keys(phrases).length - missing.length,
    effective,
    missing,
    extra,
    identity,
  };
}

function render(tag, phrases, generatedFrom) {
  const body = Object.entries(phrases)
    // Identity pairs are no-ops at runtime; dropping them keeps the chunk small.
    .filter(([en, value]) => en !== value)
    .map(([en, value]) => `  ${JSON.stringify(en)}: ${JSON.stringify(value)},`)
    .join("\n");
  return `/**
 * GENERATED by scripts/build-locale.mjs from ${generatedFrom} — do not edit by hand.
 * Edit the JSON (or re-run the translation step) and rebuild.
 *
 * English → ${tag} phrase map for the runtime translation overlay. Static
 * phrases only; interpolated strings are intentionally excluded and stay English.
 */

import type { LocaleDictionary } from "../registry";

const phrases: Record<string, string> = {
${body}
};

const dictionary: LocaleDictionary = {
  phrases,
  /** Nodes already in ${tag} are never re-translated. */
  translated: new Set(Object.values(phrases)),
};

export default dictionary;
`;
}

function build(tag, { check }) {
  const source = join(DATA, `${tag}.json`);
  if (!existsSync(source)) {
    console.error(`✗ no source for "${tag}" — expected ${source}`);
    process.exitCode = 1;
    return;
  }
  const phrases = readJson(source);
  const stats = report(tag, phrases);
  const target = join(OUT_DIR, `${tag}.ts`);
  const label = `${tag.padEnd(6)} ${String(stats.effective).padStart(4)}/${stats.total} translated`;
  const details = [
    stats.missing.length ? `${stats.missing.length} missing` : null,
    stats.extra.length ? `${stats.extra.length} unknown-key` : null,
    stats.identity.length ? `${stats.identity.length} left-as-English` : null,
  ]
    .filter(Boolean)
    .join(", ");

  if (check) {
    console.log(`· ${label}${details ? ` (${details})` : ""}`);
  } else {
    mkdirSync(OUT_DIR, { recursive: true });
    writeFileSync(target, render(tag, phrases, `scripts/locales/${tag}.json`), "utf8");
    console.log(`✓ ${label} → frontend/src/lib/i18n/locales/${tag}.ts${details ? ` (${details})` : ""}`);
  }

  if (stats.extra.length) {
    console.log(`  ⚠ keys not in scripts/locales/en.json (stale upstream copy?):`);
    stats.extra.slice(0, 10).forEach((k) => console.log(`     - ${JSON.stringify(k)}`));
  }
  if (stats.missing.length) {
    console.log(`  ⚠ untranslated keys (render in English), first 10:`);
    stats.missing.slice(0, 10).forEach((k) => console.log(`     - ${JSON.stringify(k)}`));
  }
}

/**
 * Split the canonical key list into balanced translation chunks. Long strings
 * are dealt out first so every chunk carries roughly the same work, which is
 * what lets several translators (people or agents) run in parallel and finish
 * together. Chunks are transient — regenerate them with `--split`.
 */
function split(parts) {
  const canonicalKeys = keys();
  const simplifiedPath = join(DATA, "zh-CN.json");
  const simplified = existsSync(simplifiedPath)
    ? JSON.parse(readFileSync(simplifiedPath, "utf8"))
    : null;
  const bins = Array.from({ length: parts }, () => ({ weight: 0, items: [] }));
  canonicalKeys
    .map((en, i) => ({ i, en, weight: en.length }))
    .sort((a, b) => b.weight - a.weight)
    .forEach((entry) => {
      const bin = bins.reduce((a, b) => (b.weight < a.weight ? b : a));
      bin.items.push(entry);
      bin.weight += entry.weight;
    });
  mkdirSync(join(DATA, "parts"), { recursive: true });
  bins.forEach((bin, index) => {
    bin.items.sort((a, b) => a.i - b.i);
    const suffix = `part${index + 1}.json`;
    writeFileSync(
      join(DATA, "parts", `en-${suffix}`),
      JSON.stringify(bin.items.map(({ i, en }) => ({ i, en })), null, 1) + "\n",
    );
    if (simplified) {
      writeFileSync(
        join(DATA, "parts", `zh-CN-${suffix}`),
        JSON.stringify(
          bin.items.map(({ i, en }) => ({ i, en, zh_cn: simplified[en] })),
          null,
          1,
        ) + "\n",
      );
    }
    console.log(`· parts/en-${suffix}: ${bin.items.length} entries, ${bin.weight} chars`);
  });
  console.log(`\nChunks under scripts/locales/parts/ — translate into scripts/locales/out/<tag>-part<N>.json, then:`);
  console.log(`  node scripts/merge-locale.mjs <tag> && node scripts/build-locale.mjs <tag>`);
}

/**
 * Scaffold a new language: empty source JSON + the registry entry to fill in.
 */
function add(tag) {
  const source = join(DATA, `${tag}.json`);
  if (existsSync(source)) {
    console.log(`· scripts/locales/${tag}.json already exists`);
  } else {
    writeFileSync(source, "{}\n");
    console.log(`✓ scripts/locales/${tag}.json (empty — fill it via split/merge, or by hand)`);
  }
  console.log(`\nThen register it in frontend/src/lib/i18n/registry.ts:`);
  console.log(
    [
      `  {`,
      `    tag: ${JSON.stringify(tag)},`,
      `    nativeName: "<the language, in its own script>",`,
      `    englishName: "<the language, in English>",`,
      `    shortName: "<1-2 chars, for compact slots>",`,
      `    dir: "ltr",`,
      `    load: lazy(() => import("./locales/${tag}")),`,
      `  },`,
    ].join("\n"),
  );
  console.log(`\nNothing else — the store, the overlay and the switch read that list.`);
}

const args = process.argv.slice(2);
const check = args.includes("--check");
const canonical = keys();

if (args.includes("--keys")) {
  const longest = canonical.reduce((a, b) => (b.length > a.length ? b : a), "");
  console.log(`${canonical.length} canonical English keys; longest ${longest.length} chars.`);
  console.log(`Add a key here, then translate it in every scripts/locales/<tag>.json.`);
  process.exit(0);
}

if (args.includes("--split")) {
  const at = args.indexOf("--split");
  const parts = Number(args[at + 1]) || 4;
  split(Math.max(1, Math.min(24, parts)));
  process.exit(0);
}

if (args.includes("--add")) {
  const at = args.indexOf("--add");
  const tag = args[at + 1];
  if (!tag || tag.startsWith("--")) {
    console.error("usage: node scripts/build-locale.mjs --add <tag>   e.g. --add de");
    process.exit(1);
  }
  add(tag);
  process.exit(0);
}

const requested = args.filter((a) => !a.startsWith("--"));
const targets = args.includes("--all") || requested.length === 0 ? availableLanguages() : requested;

if (!targets.length) {
  console.error("✗ nothing to build — no scripts/locales/<tag>.json found");
  process.exit(1);
}

for (const tag of targets) build(tag, { check });

if (check) {
  console.log(`\n${canonical.length} canonical keys · ${targets.length} language(s) checked`);
} else {
  console.log(`\nNext: node scripts/build-locale.mjs --check`);
}
